# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from profilerrpc import profilerrpc_pb2 as profilerrpc_dot_profilerrpc__pb2


class ProfilerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProfilerOP = channel.unary_unary(
                '/profilerrpc.Profiler/ProfilerOP',
                request_serializer=profilerrpc_dot_profilerrpc__pb2.ProfilerOPRequest.SerializeToString,
                response_deserializer=profilerrpc_dot_profilerrpc__pb2.ProfilerOPResponse.FromString,
                )


class ProfilerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProfilerOP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfilerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProfilerOP': grpc.unary_unary_rpc_method_handler(
                    servicer.ProfilerOP,
                    request_deserializer=profilerrpc_dot_profilerrpc__pb2.ProfilerOPRequest.FromString,
                    response_serializer=profilerrpc_dot_profilerrpc__pb2.ProfilerOPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profilerrpc.Profiler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Profiler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProfilerOP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profilerrpc.Profiler/ProfilerOP',
            profilerrpc_dot_profilerrpc__pb2.ProfilerOPRequest.SerializeToString,
            profilerrpc_dot_profilerrpc__pb2.ProfilerOPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
