# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profilerrpc/profilerrpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprofilerrpc/profilerrpc.proto\x12\x0bprofilerrpc\"M\n\x11ProfilerOPRequest\x12#\n\nrequest_op\x18\x01 \x01(\x0e\x32\x0f.profilerrpc.Op\x12\x13\n\x0bport_number\x18\x02 \x01(\x05\"+\n\x12ProfilerOPResponse\x12\x15\n\rprofiler_addr\x18\x01 \x01(\t*\'\n\x02Op\x12\x08\n\x04SHOW\x10\x00\x12\n\n\x06\x45NABLE\x10\x01\x12\x0b\n\x07\x44ISABLE\x10\x02\x32[\n\x08Profiler\x12O\n\nProfilerOP\x12\x1e.profilerrpc.ProfilerOPRequest\x1a\x1f.profilerrpc.ProfilerOPResponse\"\x00\x42\x31Z/github.com/longhorn/types/generated/profilerrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profilerrpc.profilerrpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/longhorn/types/generated/profilerrpc'
  _globals['_OP']._serialized_start=170
  _globals['_OP']._serialized_end=209
  _globals['_PROFILEROPREQUEST']._serialized_start=46
  _globals['_PROFILEROPREQUEST']._serialized_end=123
  _globals['_PROFILEROPRESPONSE']._serialized_start=125
  _globals['_PROFILEROPRESPONSE']._serialized_end=168
  _globals['_PROFILER']._serialized_start=211
  _globals['_PROFILER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
