# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spdkrpc/lvol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12spdkrpc/lvol.proto\x12\x07spdkrpc\"\x9e\x02\n\x04Lvol\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x11\n\tspec_size\x18\x03 \x01(\x04\x12\x13\n\x0b\x61\x63tual_size\x18\x04 \x01(\x04\x12\x0e\n\x06parent\x18\x05 \x01(\t\x12-\n\x08\x63hildren\x18\x06 \x03(\x0b\x32\x1b.spdkrpc.Lvol.ChildrenEntry\x12\x15\n\rcreation_time\x18\x07 \x01(\t\x12\x14\n\x0cuser_created\x18\x08 \x01(\x08\x12\x1a\n\x12snapshot_timestamp\x18\t \x01(\t\x12\x19\n\x11snapshot_checksum\x18\n \x01(\t\x1a/\n\rChildrenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x42\x31Z/github.com/longhorn/types/pkg/generated/spdkrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spdkrpc.lvol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/longhorn/types/pkg/generated/spdkrpc'
  _LVOL_CHILDRENENTRY._options = None
  _LVOL_CHILDRENENTRY._serialized_options = b'8\001'
  _globals['_LVOL']._serialized_start=32
  _globals['_LVOL']._serialized_end=318
  _globals['_LVOL_CHILDRENENTRY']._serialized_start=271
  _globals['_LVOL_CHILDRENENTRY']._serialized_end=318
# @@protoc_insertion_point(module_scope)
