# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spdkrpc/shard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spdkrpc import ec_pb2 as spdkrpc_dot_ec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13spdkrpc/shard.proto\x12\x07spdkrpc\x1a\x10spdkrpc/ec.proto\"\xfb\x01\n\x05Shard\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bvolume_name\x18\x02 \x01(\t\x12\x12\n\nslot_index\x18\x03 \x01(\r\x12#\n\x05state\x18\x04 \x01(\x0e\x32\x14.spdkrpc.EcSlotState\x12\x12\n\nsize_bytes\x18\x05 \x01(\x04\x12\x10\n\x08lvs_name\x18\x06 \x01(\t\x12\x10\n\x08lvs_uuid\x18\x07 \x01(\t\x12\x11\n\tbdev_name\x18\x08 \x01(\t\x12\x10\n\x08nvmf_nqn\x18\t \x01(\t\x12\x11\n\terror_msg\x18\n \x01(\t\x12\n\n\x02ip\x18\x0b \x01(\t\x12\x0c\n\x04port\x18\x0c \x01(\x05\x12\x0c\n\x04uuid\x18\r \x01(\t\"\x89\x01\n\x12ShardCreateRequest\x12\x13\n\x0bvolume_name\x18\x01 \x01(\t\x12\x12\n\nslot_index\x18\x02 \x01(\r\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\x12\x10\n\x08lvs_name\x18\x04 \x01(\t\x12\x10\n\x08lvs_uuid\x18\x05 \x01(\t\x12\x12\n\nport_count\x18\x06 \x01(\x05\"<\n\x12ShardDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x63leanup_required\x18\x02 \x01(\x08\"\x1f\n\x0fShardGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x8a\x01\n\x11ShardListResponse\x12\x36\n\x06shards\x18\x01 \x03(\x0b\x32&.spdkrpc.ShardListResponse.ShardsEntry\x1a=\n\x0bShardsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.spdkrpc.Shard:\x02\x38\x01\"0\n\x12ShardExpandRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x42\x31Z/github.com/longhorn/types/pkg/generated/spdkrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spdkrpc.shard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/longhorn/types/pkg/generated/spdkrpc'
  _SHARDLISTRESPONSE_SHARDSENTRY._options = None
  _SHARDLISTRESPONSE_SHARDSENTRY._serialized_options = b'8\001'
  _globals['_SHARD']._serialized_start=51
  _globals['_SHARD']._serialized_end=302
  _globals['_SHARDCREATEREQUEST']._serialized_start=305
  _globals['_SHARDCREATEREQUEST']._serialized_end=442
  _globals['_SHARDDELETEREQUEST']._serialized_start=444
  _globals['_SHARDDELETEREQUEST']._serialized_end=504
  _globals['_SHARDGETREQUEST']._serialized_start=506
  _globals['_SHARDGETREQUEST']._serialized_end=537
  _globals['_SHARDLISTRESPONSE']._serialized_start=540
  _globals['_SHARDLISTRESPONSE']._serialized_end=678
  _globals['_SHARDLISTRESPONSE_SHARDSENTRY']._serialized_start=617
  _globals['_SHARDLISTRESPONSE_SHARDSENTRY']._serialized_end=678
  _globals['_SHARDEXPANDREQUEST']._serialized_start=680
  _globals['_SHARDEXPANDREQUEST']._serialized_end=728
# @@protoc_insertion_point(module_scope)
